import json
from dataclasses import dataclass
from pathlib import Path

from .errors import ProjectError
from .gates import status
from .project import has_child_units, work_units
from .io import read_text
from .workflow import proposal_path, proposal_questions, proposal_is_stale


@dataclass(frozen=True)
class NextAction:
    kind: str
    stage: str | None = None
    unit: str = "default"
    reason: str = ""
    proposal: Path | None = None


def _proposal_state(project, methodology, stage_id, unit):
    path = proposal_path(project, stage_id, unit, methodology)
    if not path.is_file():
        return None, None
    try:
        data = json.loads(read_text(path))
    except json.JSONDecodeError as exc:
        raise ProjectError(f"Invalid proposal: {path}") from exc
    return path, data


def _human_review_or_block(project, methodology, stage_id, unit):
    path, proposal = _proposal_state(project, methodology, stage_id, unit)
    if not proposal:
        return None
    if proposal.get("status") == "accepted":
        return None
    if proposal.get("status") == "needs_regeneration" or proposal_is_stale(project, methodology, stage_id, unit, proposal):
        return NextAction("regenerate", stage_id, unit, "The current proposal no longer matches its authoritative upstream inputs.", path)
    if proposal_questions(project, proposal):
        return NextAction("answer_questions", stage_id, unit, "Blocking questions remain unanswered.", path)
    return NextAction("human_review", stage_id, unit, "A current AI proposal is waiting for human approval.", path)


def _unit_proposal_action(project):
    from .unit_proposals import proposal_path as unit_proposal_path, read_proposal
    path = unit_proposal_path(project)
    if not path.is_file():
        return NextAction("propose_units", None, "default", "The approved Intent has not yet been decomposed into Engineering Units.")
    data, _ = read_proposal(project)
    if data.get("status") == "accepted":
        return None
    return NextAction("human_review_units", None, "default", "The Engineering Unit proposal is waiting for human approval.", path)


def _phase_units(project, stage):
    """Return lifecycle targets for one stage, excluding the default container."""
    if stage.config.get("scope") == "project":
        return ["default"]
    return [u["key"] for u in work_units(project)]


def _phase_action(project, methodology, stage):
    """Plan one lifecycle phase as a set of Unit proposals.

    Executable stages have dedicated commands and therefore must not fall
    through the generic document-proposal path. Verification is likewise
    executed by its configured verification command before its proposal is
    generated.
    """
    targets = _phase_units(project, stage)

    if stage.action == "verify":
        # Verification is an execution step, not an AI document-generation
        # step. Run the configured command once all dependencies are current.
        for unit in targets:
            path, proposal = _proposal_state(project, methodology, stage.id, unit)
            if proposal and proposal.get("status") == "accepted":
                continue
            if proposal and proposal.get("status") == "needs_regeneration":
                return NextAction("verify", stage.id, unit, "Verification proposal is stale and must be regenerated by the verification command.", path)
            if proposal:
                if proposal_questions(project, proposal):
                    return NextAction("answer_questions", stage.id, unit, "Blocking verification questions remain unanswered.", path)
                return NextAction("human_review", stage.id, unit, "Verification proposal is waiting for human approval.", path)
            return NextAction("verify", stage.id, unit, "Run the configured verification command and generate the verification proposal.")
        return None

    if stage.action == "implementation":
        for unit in targets:
            path, proposal = _proposal_state(project, methodology, stage.id, unit)
            if proposal and proposal.get("status") == "accepted":
                continue
            if proposal and (proposal.get("status") == "needs_regeneration" or proposal_is_stale(project, methodology, stage.id, unit, proposal)):
                return NextAction("propose_implementation", stage.id, unit, "The implementation proposal no longer matches authoritative inputs.", path)
            if proposal:
                if proposal_questions(project, proposal):
                    return NextAction("answer_questions", stage.id, unit, "Blocking implementation questions remain unanswered.", path)
                return NextAction("human_review", stage.id, unit, "Implementation proposal is waiting for human approval.", path)
            return NextAction("propose_implementation", stage.id, unit, "Generate the implementation proposal from approved engineering artifacts.")
        return None
    pending = []
    blocking = []
    stale = []
    current = []
    for unit in targets:
        path, proposal = _proposal_state(project, methodology, stage.id, unit)
        if proposal and proposal.get("status") == "accepted":
            continue
        if proposal and (proposal.get("status") == "needs_regeneration" or proposal_is_stale(project, methodology, stage.id, unit, proposal)):
            stale.append((unit, path))
            continue
        if proposal:
            current.append((unit, path))
            if proposal_questions(project, proposal):
                blocking.append((unit, path))
        else:
            pending.append(unit)

    if stale:
        return NextAction("regenerate_phase", stage.id, "default", "One or more proposals no longer match authoritative inputs.")
    if pending:
        return NextAction("propose_phase", stage.id, "default", f"Generate the {stage.id} phase proposals for all applicable Engineering Units.")
    if blocking:
        return NextAction("answer_phase_questions", stage.id, "default", f"Blocking questions remain unanswered in the {stage.id} phase.")
    if current:
        return NextAction("human_review_phase", stage.id, "default", f"The {stage.id} phase is ready for human review.")
    return None


def next_action(project, methodology, unit="default"):
    """Find the next actionable transition without silently approving anything."""
    st = status(project, methodology, unit)
    intent_input = project / "engineering/intent/input.md"

    if not intent_input.is_file() and st.get("intent", {}).get("status") == "missing":
        return NextAction("human_input", "intent", "default", "Create the project's Intent before AI discovery can begin.")

    intent_status = st.get("intent", {}).get("status")
    if intent_status not in {"approved", "completed"}:
        review = _human_review_or_block(project, methodology, "intent", "default")
        if review:
            return review

    if intent_status in {"missing", "input_received"}:
        return NextAction("propose_discovery", "intent", "default", "The Intent input is ready for AI discovery.")

    if st.get("intent", {}).get("status") == "questions_pending":
        return NextAction("answer_questions", "intent", "default", "Blocking discovery questions remain unanswered.")

    # Engineering Unit decomposition is a project-level transition between
    # Governance and Unit-scoped lifecycle phases. Once child Units exist,
    # default is only the container and never receives Unit-scoped artifacts.
    for stage in methodology.stages:
        if stage.id == "intent":
            continue
        if stage.id == "context":
            # Context is handled immediately after Governance so Unit decomposition
            # is known before any Context proposal is generated.
            continue
        if stage.id == "governance":
            current = st.get(stage.id, {}).get("status")
            if current not in {"approved", "completed", "not_applicable"}:
                review = _human_review_or_block(project, methodology, stage.id, "default")
                if review:
                    return review
                return NextAction("propose", stage.id, "default", f"All dependencies for '{stage.id}' are current.")
            if not has_child_units(project):
                unit_action = _unit_proposal_action(project)
                if unit_action is not None:
                    return unit_action
            context_stage = methodology.stage("context")
            phase = _phase_action(project, methodology, context_stage)
            if phase:
                return phase
            continue
        if stage.config.get("scope") == "project":
            current = st.get(stage.id, {}).get("status")
            if current in {"approved", "completed", "not_applicable"}:
                continue
            review = _human_review_or_block(project, methodology, stage.id, "default")
            if review:
                return review
            if current in {"blocked", "needs_revalidation"}:
                return NextAction("blocked", stage.id, "default", f"Stage '{stage.id}' is blocked or requires revalidation.")
            return NextAction("propose", stage.id, "default", f"All dependencies for '{stage.id}' are current.")
        phase = _phase_action(project, methodology, stage)
        if phase:
            return phase
    return NextAction("complete", None, unit, "All lifecycle stages are current for the selected project scope.")
